name: ModeratePlugin
version: '1.0'
main: de.zbxno.moderatePlugin.ModeratePlugin
api-version: '1.21'
commands:
  moderate:
    description: moderate a player
  spawn:
    description: teleports you to spawnnn
  setjail:
    description: set the jail
  setspawn:
    description: set the spawn!